on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.16.X'

    - name: Install node modules
      run: yarn

    - name: Build
      run: yarn build

    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        rm -rf .github/ data/ docs/ src/ static/ node_modules/ .editorconfig .gitignore .prettierignore .prettierrc LICENSE README.md gatsby-config.js package.json yarn.lock
        git add .
        git commit -m "Published new version"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.TOKEN }}
        branch: gh-pages
        force: true
